import PDFDocument from "pdfkit";
import https from "https";
import http from "http";

// URL se image buffer fetch karna (S3 ya web se)
const fetchImageBuffer = (url) =>
  new Promise((resolve) => {
    const client = url.startsWith("https") ? https : http;
    const req = client.get(url, { timeout: 4000 }, (res) => {
      if (res.statusCode !== 200) return resolve(null);
      const chunks = [];
      res.on("data", (c) => chunks.push(c));
      res.on("end", () => resolve(Buffer.concat(chunks)));
    });
    req.on("error", () => resolve(null));
    req.on("timeout", () => { req.destroy(); resolve(null); });
  });

// generatePdf: Clean, centered single-page PDF banata hai
const generatePdf = async (data) => {
  return new Promise(async (res, rej) => {
    try {
      // ─── Metadata ────────────────────────────────────────────────────────────
      const title        = data?.title        || "CortexAI Document";
      const subtitle     = data?.subtitle     || "";
      const author       = data?.author       || "CortexAI";
      const primaryColor = data?.primaryColor || data?.theme?.primaryColor || "#1e3a8a";
      const secondaryColor = "#475569";
      const coverImageUrl = data?.coverImage  || null;

      // ─── Font mapping ─────────────────────────────────────────────────────────
      const fontName = data?.fontFamily || "Helvetica";
      const getFonts = (fam = "") => {
        fam = fam.toLowerCase();
        if (fam.includes("times"))   return { r: "Times-Roman",  b: "Times-Bold",    i: "Times-Italic"     };
        if (fam.includes("courier")) return { r: "Courier",      b: "Courier-Bold",  i: "Courier-Oblique"  };
        return                              { r: "Helvetica",    b: "Helvetica-Bold", i: "Helvetica-Oblique" };
      };
      const f = getFonts(fontName);

      // ─── A4 Page constants ────────────────────────────────────────────────────
      const PAGE_W    = 595.28;
      const PAGE_H    = 841.89;
      const MARGIN    = 50;
      const CONTENT_W = PAGE_W - MARGIN * 2; // 495.28

      // ─── PDF document: auto page break ON so content flows naturally ──────────
      // autoFirstPage + no bufferPages = simplest single-stream mode
      const doc = new PDFDocument({
        size: "A4",
        margin: MARGIN,
        bufferPages: false,
        info: {
          Title: title, Author: author,
          Subject: subtitle || "Generated by CortexAI",
          Producer: "CortexAI", Creator: "CortexAI",
        }
      });

      const chunks = [];
      doc.on("data",  c => chunks.push(c));
      doc.on("end",   () => res(Buffer.concat(chunks)));
      doc.on("error", e  => { console.error("PDF stream error:", e); rej(e); });

      // ─── Cover image (optional) ───────────────────────────────────────────────
      // Agar coverImage URL diya hai toh usse fetch karke top me embed karo
      if (coverImageUrl) {
        try {
          const imgBuf = await fetchImageBuffer(coverImageUrl);
          if (imgBuf) {
            // Image ko page width ke barabar center me dikhao, max 180px height
            doc.image(imgBuf, MARGIN, MARGIN, {
              width: CONTENT_W,
              height: 150,
              fit: [CONTENT_W, 150],
              align: "center",
              valign: "center",
            });
            doc.y = MARGIN + 160;
          }
        } catch (_) { /* Image fetch fail — silently skip */ }
      }

      // ─── HEADER (centered) ────────────────────────────────────────────────────
      // Title — centered, bold, primary color
      doc.fillColor(primaryColor).font(f.b).fontSize(22)
         .text(title, MARGIN, doc.y, { width: CONTENT_W, align: "center" });
      doc.moveDown(0.25);

      // Subtitle — centered, italic, secondary color
      if (subtitle) {
        doc.fillColor(secondaryColor).font(f.i).fontSize(11)
           .text(subtitle, MARGIN, doc.y, { width: CONTENT_W, align: "center" });
        doc.moveDown(0.2);
      }

      // Author + date — centered, small gray
      doc.fillColor("#9ca3af").font(f.r).fontSize(8)
         .text(
           `${author}  ·  ${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}`,
           MARGIN, doc.y, { width: CONTENT_W, align: "center" }
         );
      doc.moveDown(1.2);

      // ─── SECTIONS ────────────────────────────────────────────────────────────
      // isContentValid: section content me actual data hai ya nahi check karna
      const isContentValid = (c) => {
        if (!c || !c.type) return false;
        if (c.type === "paragraph") return !!(c.text || "").trim();
        if (c.type === "bullets")   return Array.isArray(c.items) && c.items.length > 0;
        if (c.type === "infobox")   return Array.isArray(c.pairs) && c.pairs.length > 0;
        return false;
      };

      // content field array ya object dono handle karna — LLM kabhi kabhi array deta hai
      const getContent = (section) => {
        const c = section.content;
        if (!c) return null;
        if (Array.isArray(c)) return c.find(item => isContentValid(item)) || null;
        return isContentValid(c) ? c : null;
      };

      const sections = (data?.sections || [])
        .slice(0, 5)
        .map(s => ({ ...s, content: getContent(s) }))
        .filter(s => s.content !== null);

      sections.forEach((section) => {
        const c = section.content;

        // Section heading — left aligned, bold, primary color
        if (section.heading) {
          doc.fillColor(primaryColor).font(f.b).fontSize(12)
             .text(section.heading, MARGIN, doc.y, { width: CONTENT_W });
          doc.moveDown(0.4);
        }

        if (c.type === "paragraph") {
          // ── Paragraph ────────────────────────────────────────────────────────
          doc.fillColor("#1f2937").font(f.r).fontSize(10)
             .text((c.text || "").trim(), MARGIN, doc.y, {
               width: CONTENT_W, align: "justify", lineGap: 3,
             });
          doc.moveDown(0.8);

        } else if (c.type === "bullets") {
          // ── Bullet list ───────────────────────────────────────────────────────
          const items = (c.items || []).slice(0, 8);
          items.forEach((item) => {
            const bY = doc.y;
            // Bullet dot — separate call at fixed X so text doesn't overlap
            doc.fillColor(primaryColor).font(f.b).fontSize(11)
               .text("·", MARGIN + 4, bY, { width: 14 });
            // Bullet text — starts indented
            doc.fillColor("#1f2937").font(f.r).fontSize(10)
               .text(String(item), MARGIN + 18, bY, { width: CONTENT_W - 18, lineGap: 2 });
            doc.moveDown(0.3);
          });
          doc.moveDown(0.3);

        } else if (c.type === "infobox") {
          // ── Info box (key-value table) ────────────────────────────────────────
          const ROW_H = 19;
          const KEY_W = 160;
          const pairs = (c.pairs || []).slice(0, 10);
          pairs.forEach((pair, idx) => {
            const y = doc.y;
            // Alternating background stripe
            if (idx % 2 === 0) {
              doc.rect(MARGIN, y, CONTENT_W, ROW_H).fillOpacity(0.06).fill("#64748b");
              doc.fillOpacity(1);
            }
            doc.fillColor(primaryColor).font(f.b).fontSize(9)
               .text(String(pair.key || ""), MARGIN + 5, y + 4, { width: KEY_W - 5, ellipsis: true });
            doc.fillColor("#111827").font(f.r).fontSize(9)
               .text(String(pair.value || ""), MARGIN + KEY_W, y + 4, { width: CONTENT_W - KEY_W - 5, ellipsis: true });
            doc.y = y + ROW_H;
          });
          doc.moveDown(0.8);
        }

        doc.moveDown(0.3);
      });

      // ─── Footer — sirf tab likhna jab Y safe range me ho ────────────────────
      // PDFKit automatically adds page when Y > PAGE_H - MARGIN (796px)
      // Footer 796px se neeche nahi jaana chahiye warna blank page aayegi
      const safeFooterY = PAGE_H - MARGIN - 18; // = 773.89 — safe zone
      if (doc.y < safeFooterY - 20) {
        // Sirf agar content abhi 754px se upar khatam hua ho toh footer dikhao
        doc.fillColor("#d1d5db").font(f.r).fontSize(7.5)
           .text("Powered by CortexAI", MARGIN, safeFooterY, {
             width: CONTENT_W, align: "center", lineBreak: false,
           });
      }

      doc.end();

    } catch (err) {
      console.error("generatePdf error:", err);
      rej(err);
    }
  });
};

export default generatePdf;